### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ykris45**
Change .io to .com

### CODE REVIEW

**Comment by tzarebczan** [comment]
@ykris45 thank you for the PR but we'll be doing an internal pass at all .io references first ;)

**Comment by ykris45** [comment]
its the task from julie Mr Thomas via DM

**Comment by jsigwart** [comment]
Yes, this is my request and I’ll review it. Thanks, both of you!

**Comment by ykris45** [comment]
you welcome my auntie and Mr Thomas

**Pull request merged**
